/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarioRouteImport } from './routes/mario'
import { Route as IndexRouteImport } from './routes/index'

const MarioRoute = MarioRouteImport.update({
  id: '/mario',
  path: '/mario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mario': typeof MarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mario': typeof MarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mario': typeof MarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mario'
  id: '__root__' | '/' | '/mario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarioRoute: typeof MarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mario': {
      id: '/mario'
      path: '/mario'
      fullPath: '/mario'
      preLoaderRoute: typeof MarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarioRoute: MarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
